# Generated by Django 4.2.2 on 2023-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdetail',
            name='password',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='labdetail',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='labdetail',
            name='email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='labdetail',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='labdetail',
            name='phone_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
