# Generated by Django 4.2.2 on 2023-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_labdetail_password_alter_labdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='phone_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
