# Generated by Django 4.2.2 on 2023-06-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_patientdetail_gender_alter_patientdetail_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetail',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='patienttestdetail',
            old_name='bill_id',
            new_name='bill',
        ),
        migrations.RenameField(
            model_name='patienttestdetail',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='patienttestdetail',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patienttestdetail',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testdetail',
            old_name='lab_id',
            new_name='lab',
        ),
    ]
