# Generated by Django 4.2.2 on 2023-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0004_rename_lab_id_patientdetail_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testdetail',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
