# Generated by Django 4.2.2 on 2023-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0005_patientdetail_is_deleted_testdetail_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='invoice',
            field=models.TextField(default='', max_length=500),
        ),
    ]
